### PR TITLE
Fix code style issues

### LINKED ISSUE #30: [TASK] Fix code style issues in contributing docs
## Task Context

The Codacy software which helps to determine the project's code quality is currently reporting a B score for this project.
This is mostly due in part to code style issues it is reporting for the contributing docs which is written in Markdown.

Click on the following link to view the code style issues that needs to be fixed: https://app.codacy.com/gh/jmakhack/myanimelist-cli/issues?categoryType=CodeStyle

## Acceptance Criteria
1. Fix the 9 code style issues mentioned in the Codacy link (while not adding new ones)
2. Rename `CONTRIBUTION.md` to `CONTRIBUTING.md` which is the GitHub standard

## Additional Context

For any questions or discussions, join the [Discord](https://discord.gg/RTgxfFW9mS) to meet and engage with other contributors!

[Discord](https://discord.gg/RTgxfFW9mS)

### PR DESCRIPTION
**Pull request by Nikhil-1503**
## Associated Issue

Closes #30

## Implemented Solution

Added spaces where necessary and changed autolink by adding mailto protocol

### CODE REVIEW

**Comment by Nikhil-1503** [comment]
Umm, I think it should have fixed all issues, but it's showing I didn't fix any.

**Comment by jmakhack** [comment]
> Umm, I think it should have fixed all issues, but it's showing I didn't fix any.

Oh strange, it looks like there is an issue with the code style checker. I'll take a look into it but in the meanwhile, I've marked your pull request as hacktoberfest-accepted. Thanks for the contribution! :)

**Comment by jmakhack** [comment]
@all-contributors please add @Nikhil-1503 for maintenance

**Comment by Nikhil-1503** [comment]
Thank you for the opportunity.

**Review by jmakhack — APPROVED** [review]

**Pull request merged**
