### PR TITLE
Fixed code style issues in task template

### LINKED ISSUE #32: [TASK] Fix code style issues in task template
## Task Context

With the introduction of a new task template, there was also a code style issue added.

This task is to remove that code style issue in an effort to improve the overall quality of the project files.

## Acceptance Criteria

Fix the Codacy reported issue here: https://app.codacy.com/gh/jmakhack/myanimelist-cli/file/76787783830/issues/source?bid=22863233&fileBranchId=22863233#l4

## Additional Context

The task template can be found here: [task.md](https://github.com/jmakhack/myanimelist-cli/blob/master/.github/ISSUE_TEMPLATE/task.md)

For any questions or discussions, join the [Discord](https://discord.gg/RTgxfFW9mS) to meet and engage with other contributors!

[Discord](https://discord.gg/RTgxfFW9mS)

### PR DESCRIPTION
**Pull request by VividhPandey003**
Signed-off-by: Vividh Pandey <vividh.pandey.13@gmail.com>

## Associated Issue

image
Fixes the code style issue '[no-undefined-references] Found reference to undefined definition'

Closes #32 

## Implemented Solution

Removing the extra whitespace in line no 4 `title: "[TASK] "` solves the issue.
This was done to improve the overall quality of the project files.

### CODE REVIEW

**Review by jmakhack — CHANGES_REQUESTED** [review]
Hey @VividhPandey003, it doesn't look like this solved the issue.

https://app.codacy.com/gh/jmakhack/myanimelist-cli/pullRequest?prid=10280332#fixedIssuesView reports that no code style issues were fixed. You can check that link after making other changes to see if the issue is fixed.

------

If it helps, you can also reference the [bug report template](https://github.com/jmakhack/myanimelist-cli/blob/master/.github/ISSUE_TEMPLATE/bug-report.md?plain=1) and the [feature request template](https://github.com/jmakhack/myanimelist-cli/blob/master/.github/ISSUE_TEMPLATE/feature-request.md?plain=1) which have zero code style issues.

**Comment by jmakhack** [comment]
Hey @VividhPandey003. Looks like there's also an issue with the code style checker so any fixes might not show up. See https://github.com/jmakhack/myanimelist-cli/pull/37#issuecomment-1264311965 where another programmer is having this issue.

I'll take a look into why the style checker is failing but in the meantime, I've marked your pull request as hacktoberfest-accepted. Thanks for looking into this! :)

**Comment by jmakhack** [comment]
@all-contributors please add @VividhPandey003 for maintenance

**Comment by VividhPandey003** [comment]
> @jmakhack
> 
> I've put up [a pull request](https://github.com/jmakhack/myanimelist-cli/pull/39) to add @VividhPandey003! 🎉

Thank you @jmakhack. Really appreciate it😄😁

**Comment by jmakhack** [comment]
Fixed the issue with Codacy not displaying the correct results.

If the issue is fixed, it should show up here: https://app.codacy.com/gh/jmakhack/myanimelist-cli/pullRequest?prid=10280332

**Pull request closed without merging**
